# Generated by Django 4.1.7 on 2023-03-04 07:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата последнего редактирования",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(9, "Edu"), (10, "Job")], default=9
                    ),
                ),
                ("counter", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Growth",
            fields=[
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата последнего редактирования",
                    ),
                ),
                ("counter", models.PositiveIntegerField()),
                ("period", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "end_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="graph.node",
                    ),
                ),
                (
                    "start_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="graph.node",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
