# Generated by Django 4.1.7 on 2023-03-10 09:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.SmallIntegerField(choices=[(9, 'Edu'), (10, 'Job')], default=10)),
                ('counter', models.PositiveIntegerField()),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Growth',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('counter', models.PositiveIntegerField()),
                ('period', models.DecimalField(decimal_places=2, max_digits=5)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='graph.node')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='graph.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
