# Generated by Django 4.1.7 on 2023-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_alter_growth_created_at_alter_growth_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Временный код'),
        ),
    ]
